"""project table fix

Revision ID: 3cc62b061608
Revises: 8187d4cb69e2
Create Date: 2020-02-11 15:02:10.840750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3cc62b061608"
down_revision = "8187d4cb69e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customer",
        "payment_account",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "employee", "profession", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "person", "first_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "person", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.drop_index("ix_person_email", table_name="person")
    op.drop_index("ix_person_phone", table_name="person")
    op.create_unique_constraint(None, "person", ["phone"])
    op.create_unique_constraint(None, "person", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "person", type_="unique")
    op.drop_constraint(None, "person", type_="unique")
    op.create_index("ix_person_phone", "person", ["phone"], unique=True)
    op.create_index("ix_person_email", "person", ["email"], unique=True)
    op.alter_column(
        "person", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "person", "first_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "employee", "profession", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "customer",
        "payment_account",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    # ### end Alembic commands ###
