"""project table fix


Revision ID: 598394baffcf
Revises: 3cc62b061608
Create Date: 2020-02-11 17:12:05.395158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "598394baffcf"
down_revision = "3cc62b061608"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer", sa.Column("person_id", sa.Integer(), nullable=True))
    op.drop_constraint("customer_owner_id_fkey", "customer", type_="foreignkey")
    op.create_foreign_key(None, "customer", "person", ["person_id"], ["id"])
    op.drop_column("customer", "owner_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "customer", type_="foreignkey")
    op.create_foreign_key(
        "customer_owner_id_fkey", "customer", "person", ["owner_id"], ["id"]
    )
    op.drop_column("customer", "person_id")
    # ### end Alembic commands ###
