"""person employee customer table

Revision ID: 60bc96d2c72e
Revises: 
Create Date: 2020-02-11 14:31:57.948066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60bc96d2c72e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("patronymic", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_person_email"), "person", ["email"], unique=True)
    op.create_index(op.f("ix_person_phone"), "person", ["phone"], unique=True)
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "customer_type",
            sa.Enum("organization", "individual", name="customertypeenum"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("organization_name", sa.String(length=50), nullable=True),
        sa.Column("payment_account", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["person.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_name"),
        sa.UniqueConstraint("payment_account"),
    )
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("profession", sa.String(length=50), nullable=True),
        sa.Column("is_manager", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employee")
    op.drop_table("customer")
    op.drop_index(op.f("ix_person_phone"), table_name="person")
    op.drop_index(op.f("ix_person_email"), table_name="person")
    op.drop_table("person")
    # ### end Alembic commands ###
