"""empty message

Revision ID: 84d50795f993
Revises: 3ee8160ec62f
Create Date: 2020-02-14 15:59:48.142777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "84d50795f993"
down_revision = "3ee8160ec62f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("work_started", sa.Boolean(), nullable=True))
    op.drop_column("project", "start_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "start_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("project", "work_started")
    # ### end Alembic commands ###
