"""empty message

Revision ID: b0c1692627cf
Revises: 2f05fd2f65a2
Create Date: 2020-02-13 10:23:24.658938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b0c1692627cf"
down_revision = "2f05fd2f65a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("contract", sa.String(length=200), nullable=True)
    )
    op.add_column("project", sa.Column("has_contract", sa.Boolean(), nullable=True))
    op.add_column("project", sa.Column("has_plan", sa.Boolean(), nullable=True))
    op.add_column("project", sa.Column("price", sa.Integer(), nullable=True))
    op.alter_column(
        "project",
        "expiration_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "project", "start_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project", "start_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "project",
        "expiration_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column("project", "price")
    op.drop_column("project", "has_plan")
    op.drop_column("project", "has_contract")
    op.drop_column("project", "contract")
    # ### end Alembic commands ###
